In [1]:
import torch
import pandas as pd
import numpy as np
from transformers import BertTokenizer, BertForSequenceClassification

In [2]:
df = pd.read_csv('./imdb_movie_reviews.csv')
df = df.drop('sentiment',axis=1)
df.head()

                                                text
0  My daughter liked it but I was aghast, that a ...
1  I... No words. No words can describe this. I w...
2  this film is basically a poor take on the old ...
3  This is a terrible movie, and I'm not even sur...
4  First of all this movie is a piece of reality ...

In [3]:
tokenizer = BertTokenizer.from_pretrained('nlptown/bert-base-multilingual-uncased-sentiment')
model = BertForSequenceClassification.from_pretrained('nlptown/bert-base-multilingual-uncased-sentiment')
def sentiment_movie_score(movie_review):
	token = tokenizer.encode(movie_review, return_tensors = 'pt')
	result = model(token)
	return int(torch.argmax(result.logits))+1
df['sentiment'] = df['text'].apply(lambda x: sentiment_movie_score(x[:512]))
df.head()

tokenizer_config.json:   0%|          | 0.00/39.0 [00:00<?, ?B/s]

C:\Users\74267\.conda\envs\pat-nlp-lifecycle\lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\74267\.cache\huggingface\hub\models--nlptown--bert-base-multilingual-uncased-sentiment. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

vocab.txt: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/953 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/669M [00:00<?, ?B/s]

                                                text  sentiment
0  My daughter liked it but I was aghast, that a ...          3
1  I... No words. No words can describe this. I w...          1
2  this film is basically a poor take on the old ...          2
3  This is a terrible movie, and I'm not even sur...          1
4  First of all this movie is a piece of reality ...          4